/**
 * Hotel detail data keyed by canonical slug.
 *
 * Names and core framing are derived from the existing detail pages
 * (*.tsx SEO copy + siwa-hotels.json) and the listing page copy already
 * shipped in siwa-oasis-accommodation.tsx / north-coast-accommodation.tsx.
 * Rooms, reviews, and operational facts come from the approved design
 * reference. Used by the new /hotel-detail template.
 */

import { canonicalHotelSlug } from "./route-maps";

export type Destination = "siwa-oasis" | "north-coast";

export interface HotelRoom {
  name: string;
  type: string;
  desc: string;
  sqm: string;
  beds: string;
  occupancy: string;
  price: number; // € / night — base rate for the listing
  image?: string; // Optional room photograph URL
}

export interface HotelFact {
  label: string;
  value: string;
}

export interface HotelReview {
  name: string;
  origin: string;
  text: string;
}

export interface HotelLocationLink {
  label: string;
  value: string;
}

export interface HotelDetail {
  slug: string;
  destination: Destination;
  name: string;
  nameMain: string;
  nameItalic?: string;
  tagLine: string;
  heroMeta: string[];
  /** Gradient class used in listing + detail hero placeholders. */
  gradient: string;
  intro: string[];
  eyebrow: string;
  headline: string;
  headlineItalic: string;
  facts: HotelFact[];
  amenities: string[];
  rooms: HotelRoom[];
  location: HotelLocationLink[];
  reviews: HotelReview[];
  gallerySize: number;
  /** Cover photo shown behind the detail-page hero. Sourced from the
   *  admin "Card image" (hotels.imageUrl). Optional — falls back to the
   *  gradient when absent. */
  coverImage?: string;
  /** Ordered gallery image URLs shown in the "View all photos" lightbox. */
  gallery?: string[];
  /** Slugs of 3 sibling properties to show in "Other properties". */
  related: string[];
  basePrice: number;
  /** Human-readable from-line (e.g. "€320 / night · full board"). */
  priceLabel: string;
  /** Displayed in breadcrumb. */
  breadcrumbLabel: string;
  /** Displayed in hero tag chip. */
  heroTag: string;
  /**
   * Tab.travel embedded booking widget identifier. When set on a Siwa
   * property, the detail page's Siwa booking panel renders the Tab.travel
   * widget in place of the static form. Leave undefined to fall back to
   * the /enquire route.
   */
  tabTravelWidgetId?: string;
}

const siwaDestGradient =
  "bg-[linear-gradient(155deg,#1a3a52_0%,#0F2436_50%,#0a1e2e_100%)]";
const coastalGradient =
  "bg-[linear-gradient(155deg,#0F2436_0%,#2F6F8F_55%,#1a5a7a_100%)]";

export const HOTEL_DETAILS: Record<string, HotelDetail> = {
  // ─── SIWA ───────────────────────────────────────────────────
  "adrere-amellal": {
    slug: "adrere-amellal",
    destination: "siwa-oasis",
    name: "Adrère Amellal",
    nameMain: "Adrère",
    nameItalic: "Amellal.",
    tagLine: "Eco Lodge · No electricity · Salt lake front",
    heroTag: "Eco Lodge · No electricity · Salt lake front",
    heroMeta: ["Siwa Oasis, Egypt", "White Mountain", "Est. 1997", "36 rooms", "From €320 / night"],
    breadcrumbLabel: "Adrère Amellal",
    gradient: siwaDestGradient,
    eyebrow: "The property",
    headline: "Egypt's most celebrated",
    headlineItalic: "eco-lodge.",
    intro: [
      "Built entirely from karsheef — the local salt rock that has been used in Siwa for centuries — into the face of the White Mountain at the edge of the great salt lake. No electricity. No internet. No noise except the wind off the sand sea and the sound of oil lamps settling at dusk.",
      "Adrère Amellal has been welcoming guests since 1997, when the concept of sustainable luxury in Egypt was not a category but an act of conviction. It remains the standard by which all other desert lodges are measured — not because of what it offers, but because of what it refuses to compromise.",
      "Staying here is a deliberate decision to remove yourself from everything for a few days. The guests who love it most are those who arrive ready to be bored in the best possible way, and leave having discovered that boredom was never what they found.",
    ],
    facts: [
      { label: "Property type", value: "Eco Lodge" },
      { label: "Location", value: "White Mountain, Siwa Oasis" },
      { label: "Total rooms", value: "36 rooms & suites" },
      { label: "Electricity", value: "None — oil lamp lighting" },
      { label: "Internet", value: "Not available on property" },
      { label: "Meals", value: "Full board included" },
      { label: "Check-in", value: "From 2:00 PM" },
      { label: "Check-out", value: "By 12:00 PM" },
      { label: "Min. stay", value: "2 nights" },
    ],
    amenities: [
      "Full board — breakfast, lunch, dinner",
      "Natural salt lake swimming access",
      "Organic farm produce for all meals",
      "Oil lamp lighting throughout",
      "Daily room service",
      "Desert excursions on request",
      "Traditional Siwan welcome tea",
      "Sand bath healing session (once per stay)",
      "Cleopatra Spring access",
      "Star-gazing terrace",
      "Library & reading rooms",
      "Airport/city transfer available",
    ],
    rooms: [
      {
        name: "Garden Room",
        type: "Standard · Garden view",
        desc: "Carved into the karsheef walls, with direct access to the garden courtyard. Cool in the afternoon, warm in the evening. The most connected room to the daily rhythm of the lodge.",
        sqm: "~28 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 320,
      },
      {
        name: "Lake View Room",
        type: "Superior · Salt lake panorama",
        desc: "Higher in the mountain with a terrace that faces the salt lake directly. Sunrise here is extraordinary — the light moves across the water in a way you'll want to sit and watch without speaking.",
        sqm: "~34 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 380,
      },
      {
        name: "White Mountain Suite",
        type: "Suite · Panoramic · Private terrace",
        desc: "The most private and elevated accommodation at Adrère Amellal. A separate sitting room, a generous terrace overlooking both the lake and the desert, and a quality of solitude that guests return for specifically.",
        sqm: "~52 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 520,
      },
    ],
    location: [
      { label: "From Cairo", value: "~8 hours by private vehicle via the Western Desert road" },
      { label: "From Marsa Matrouh", value: "~3 hours by private 4×4 via desert sand road" },
      { label: "From Siwa town centre", value: "~15 minutes by vehicle" },
      { label: "Transfer arranged by", value: "Soléi — included in booking or added separately" },
    ],
    reviews: [
      {
        name: "Sophie R.",
        origin: "France · Stayed October 2024",
        text: "We've stayed in luxury hotels on four continents. Adrère Amellal is unlike any of them. The absence of electricity sounds like a deprivation until you spend your first evening by oil lamp and realise it's the most beautiful light you've ever eaten dinner by.",
      },
      {
        name: "James & Marta K.",
        origin: "United Kingdom · Stayed March 2024",
        text: "We booked three nights and extended to five. There's something about the rhythm of this place — the food, the silence, the salt lake at sunset — that makes the idea of leaving feel genuinely wrong. We'll be back.",
      },
      {
        name: "Amira S.",
        origin: "UAE · Stayed January 2025",
        text: "I'm Egyptian and had never been to Siwa. I was ashamed of that before I arrived and grateful for it after — because I got to discover it for the first time as an adult, with the context to appreciate what I was seeing. Adrère Amellal is how Egypt should be experienced.",
      },
    ],
    gallerySize: 14,
    related: ["taziry-ecolodge", "solei-old-town", "ghaliet-ecolodge-spa"],
    basePrice: 320,
    priceLabel: "/ night · full board",
  },

  "taziry-ecolodge": {
    slug: "taziry-ecolodge",
    destination: "siwa-oasis",
    name: "Taziry Eco-Lodge",
    nameMain: "Taziry",
    nameItalic: "Eco-Lodge.",
    tagLine: "Boutique Eco Lodge · Solar · Siwan Cuisine",
    heroTag: "Eco Lodge · 100% solar · Salt lake views",
    heroMeta: ["Siwa Oasis, Egypt", "Salt lake edge", "18 rooms & chalets", "From €180 / night"],
    breadcrumbLabel: "Taziry Eco-Lodge",
    gradient: "bg-[linear-gradient(155deg,#0F2436_0%,#1a4060_60%,#1a3a52_100%)]",
    eyebrow: "The property",
    headline: "A boutique lodge powered",
    headlineItalic: "entirely by the sun.",
    intro: [
      "Taziry is a boutique eco-lodge powered entirely by solar energy — handcrafted rooms, family-prepared Siwan cuisine, and uninterrupted views of the salt lake. More accessible than Adrère Amellal, no less considered.",
      "The lodge was built by a husband-and-wife team who live on-site and run the kitchen themselves. That care shows up in details most places skip — the way the bread is baked fresh each morning, how the evenings at the salt-water pool are genuinely quiet, the fact that the stars overhead are the point, not a marketing claim.",
    ],
    facts: [
      { label: "Property type", value: "Boutique eco-lodge" },
      { label: "Location", value: "Siwa Oasis · Salt lake edge" },
      { label: "Total rooms", value: "18 rooms & chalets" },
      { label: "Power", value: "100% solar" },
      { label: "Pool", value: "Natural salt water" },
      { label: "Meals", value: "Half or full board" },
      { label: "Check-in", value: "From 2:00 PM" },
      { label: "Check-out", value: "By 11:00 AM" },
      { label: "Min. stay", value: "1 night" },
    ],
    amenities: [
      "Salt-water pool",
      "Family-run kitchen",
      "Siwan and Mediterranean menus",
      "Solar-heated showers",
      "Lake-view terraces",
      "Guided salt-lake swim",
      "Bicycles available",
      "Bedouin dinner on request",
      "Airport transfer arranged",
    ],
    rooms: [
      {
        name: "Garden Bungalow",
        type: "Standard · Palm garden",
        desc: "Earthen-walled bungalow set among the lodge's date palms. Warm, unhurried, and close to the salt pool.",
        sqm: "~26 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 180,
      },
      {
        name: "Lakeside Chalet",
        type: "Superior · Lake-facing terrace",
        desc: "A private chalet with a wooden terrace facing the salt lake directly. Watch the light change from dawn to dusk without leaving the room.",
        sqm: "~36 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 240,
      },
      {
        name: "Family Suite",
        type: "Suite · 2 bedrooms · Garden",
        desc: "Two-bedroom suite with a shared sitting area. Built for families who want to stay together without sharing a bed.",
        sqm: "~54 m²",
        beds: "1 king + 2 singles",
        occupancy: "Up to 4 guests",
        price: 320,
      },
    ],
    location: [
      { label: "From Cairo", value: "~8 hours by private vehicle" },
      { label: "From Marsa Matrouh", value: "~3 hours by private 4×4" },
      { label: "From Siwa town centre", value: "~10 minutes" },
      { label: "Transfer arranged by", value: "Soléi — on request" },
    ],
    reviews: [
      {
        name: "Laura B.",
        origin: "Italy · Stayed November 2024",
        text: "The food alone would make me come back. Three meals a day, prepared by the family, and not one of them felt like a hotel meal. This place is run by people, not by a brand.",
      },
      {
        name: "Felix W.",
        origin: "Germany · Stayed February 2025",
        text: "Quiet in the right way. You can hear the wind over the salt lake from the pool. I didn't open a book for three days — just sat.",
      },
    ],
    gallerySize: 11,
    related: ["adrere-amellal", "ghaliet-ecolodge-spa", "talist-siwa"],
    basePrice: 180,
    priceLabel: "/ night",
  },

  "solei-old-town": {
    slug: "solei-old-town",
    destination: "siwa-oasis",
    name: "Soléi Old Town",
    nameMain: "Soléi",
    nameItalic: "Old Town.",
    tagLine: "Heritage Stay · Historic Center · Shali Views",
    heroTag: "Soléi Owned · Heritage Stay · Old City",
    heroMeta: ["Siwa Oasis, Egypt", "Old Medina", "12 rooms", "From €145 / night"],
    breadcrumbLabel: "Soléi Old Town",
    gradient: "bg-[linear-gradient(155deg,#1a3a52_0%,#1e3a50_60%,#0F2436_100%)]",
    eyebrow: "Soléi Owned",
    headline: "Handcrafted clay rooms in",
    headlineItalic: "Siwa's historic heart.",
    intro: [
      "Soléi Old Town sits in the centre of Siwa's historic medina — a few steps from the karsheef walls of the Shali fortress and the traditional market. Rooms are handcrafted clay, cool in the afternoon, gently lit in the evening. The rooftop terrace overlooks the old city at dusk, which is the best time to sit up there without saying much.",
      "This is one of our own properties. Everything — the service, the architecture, the menu, the evenings we organise quietly for guests — is handled by our team directly. You can feel the difference, and so can we.",
    ],
    facts: [
      { label: "Property type", value: "Heritage stay — Soléi-owned" },
      { label: "Location", value: "Old Medina, Siwa Oasis" },
      { label: "Total rooms", value: "12 handcrafted rooms" },
      { label: "Architecture", value: "Traditional karsheef clay" },
      { label: "Rooftop", value: "Shali fortress views" },
      { label: "Meals", value: "Breakfast included · local menu" },
      { label: "Check-in", value: "From 2:00 PM" },
      { label: "Check-out", value: "By 11:00 AM" },
      { label: "Min. stay", value: "1 night" },
    ],
    amenities: [
      "Rooftop terrace with Shali views",
      "Daily stargazing session",
      "Family-coordinated activities",
      "Traditional Siwan breakfast",
      "Local market walking tour",
      "Salt cave access arranged",
      "Bicycles available",
      "24-hour reception",
      "Airport/city transfer on request",
    ],
    rooms: [
      {
        name: "Heritage Room",
        type: "Standard · Old city",
        desc: "A traditional clay-walled room with a handcrafted bed frame and a small window onto the medina.",
        sqm: "~22 m²",
        beds: "Queen bed",
        occupancy: "Up to 2 guests",
        price: 145,
      },
      {
        name: "Shali View Room",
        type: "Superior · Fortress-facing",
        desc: "A slightly larger room with a window seat positioned directly toward the Shali ruins. Best at sunset.",
        sqm: "~28 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 185,
      },
      {
        name: "Rooftop Suite",
        type: "Suite · Private rooftop corner",
        desc: "A two-room suite at the top of the building with direct access to a private section of the rooftop terrace.",
        sqm: "~46 m²",
        beds: "King bed",
        occupancy: "Up to 3 guests",
        price: 260,
      },
    ],
    location: [
      { label: "From Cairo", value: "~8 hours by private vehicle" },
      { label: "From Marsa Matrouh", value: "~3 hours by private 4×4" },
      { label: "Shali fortress", value: "2-minute walk" },
      { label: "Transfer arranged by", value: "Soléi" },
    ],
    reviews: [
      {
        name: "Yasmin H.",
        origin: "Egypt · Stayed December 2024",
        text: "Everything about this place feels considered. The team clearly lives here — nothing was rushed or impersonal. We extended by two nights.",
      },
      {
        name: "Anton & Greta M.",
        origin: "Sweden · Stayed October 2024",
        text: "The rooftop at sunset is what we came for — and somehow still better than we'd imagined. The breakfast alone is worth the stay.",
      },
    ],
    gallerySize: 9,
    related: ["solei-royal", "adrere-amellal", "taziry-ecolodge"],
    basePrice: 145,
    priceLabel: "/ night",
  },

  "solei-royal": {
    slug: "solei-royal",
    destination: "siwa-oasis",
    name: "Soléi Royal",
    nameMain: "Soléi",
    nameItalic: "Royal.",
    tagLine: "Royal Villa · 5 Bedrooms · 4 Pools",
    heroTag: "Soléi Owned · Royal Villa · Whole-property bookings",
    heroMeta: ["Siwa Oasis, Egypt", "Private estate", "5 bedrooms · 4 pools", "From €195 / night"],
    breadcrumbLabel: "Soléi Royal",
    gradient: "bg-[linear-gradient(155deg,#0F2436_0%,#0d2a40_60%,#1a3a52_100%)]",
    eyebrow: "Soléi Owned",
    headline: "An exclusive royal villa —",
    headlineItalic: "the whole property, yours.",
    intro: [
      "Soléi Royal is the most private accommodation we offer. Five bedrooms, four pools, private natural springs, and a personal butler. It is designed for families or small groups who want the entire property to themselves — not a room within a hotel, but an estate they can organise around their own pace.",
      "Guests typically book it as a whole villa for three to seven nights. Meals can be arranged by our private chef, and our team coordinates every excursion, transfer, and small detail so that nothing inside the property requires a decision from you.",
    ],
    facts: [
      { label: "Property type", value: "Private villa — Soléi-owned" },
      { label: "Bedrooms", value: "5 (sleeps up to 10)" },
      { label: "Pools", value: "4 (incl. natural spring)" },
      { label: "Service", value: "Dedicated butler + chef" },
      { label: "Booking style", value: "Whole-villa only" },
      { label: "Meals", value: "Private chef · à la carte" },
      { label: "Check-in", value: "Flexible" },
      { label: "Min. stay", value: "3 nights" },
      { label: "Max. stay", value: "Unlimited" },
    ],
    amenities: [
      "Whole-villa exclusivity",
      "Natural spring pool",
      "3 additional pools",
      "Personal butler service",
      "Private chef (on request)",
      "Daily housekeeping",
      "Walled private garden",
      "Desert excursions included",
      "All transfers included",
    ],
    rooms: [
      {
        name: "Whole Villa — 5 Bedrooms",
        type: "Private estate · Full board",
        desc: "The entire property, including all five bedrooms, four pools, the natural spring, walled garden, and dedicated service team. Priced as a whole-villa rate per night.",
        sqm: "~1,100 m² built",
        beds: "5 bedrooms · sleeps 10",
        occupancy: "Up to 10 guests",
        price: 195,
      },
    ],
    location: [
      { label: "From Cairo", value: "~8 hours by private vehicle — included" },
      { label: "From Marsa Matrouh", value: "~3 hours by private 4×4 — included" },
      { label: "From Siwa town centre", value: "~12 minutes" },
      { label: "Transfer arranged by", value: "Soléi — fully included" },
    ],
    reviews: [
      {
        name: "The Al-Farsi family",
        origin: "Saudi Arabia · Stayed March 2025",
        text: "We rented the entire villa for nine nights. Three generations, nobody felt crowded, and the staff read the family's rhythm inside of two days. The chef alone was worth the journey.",
      },
      {
        name: "Private group · 6 guests",
        origin: "United Kingdom · Stayed November 2024",
        text: "Six of us celebrating a fiftieth birthday. The pools, the garden, the stars — it stopped feeling like a hotel on the second night. Everyone is already talking about coming back.",
      },
    ],
    gallerySize: 16,
    related: ["solei-old-town", "adrere-amellal", "taziry-ecolodge"],
    basePrice: 195,
    priceLabel: "/ night · whole villa",
  },

  "solei-desert-retreat": {
    slug: "solei-desert-retreat",
    destination: "siwa-oasis",
    name: "Soléi Desert Retreat",
    nameMain: "Soléi",
    nameItalic: "Desert Retreat.",
    tagLine: "Desert Lodge · Salt Flats · Completely Remote",
    heroTag: "Soléi Owned · Desert Lodge · 3 rooms only",
    heroMeta: ["Great Sand Sea, Egypt", "3 rooms", "Full board", "From €240 / night"],
    breadcrumbLabel: "Soléi Desert Retreat",
    gradient: "bg-[linear-gradient(155deg,#0a1e2e_0%,#1a3a52_45%,#0F2436_100%)]",
    eyebrow: "Soléi Owned",
    headline: "A small desert lodge",
    headlineItalic: "with no light for hours.",
    intro: [
      "Soléi Desert Retreat sits an hour outside Siwa town, on the edge of the Great Sand Sea where the dunes give way to a salt flat that mirrors the sky. Three rooms only — built low, in clay and palm wood — opening onto a shared fire pit and a stargazing deck. There is no light pollution, no signal worth checking, and dinner is fire-cooked and served when the sky turns purple.",
      "This is one of our own properties. Full board because there is nowhere else to eat; private guides because the desert is the entire reason you are there. Three rooms means three couples or a single family. Quiet by design.",
    ],
    facts: [
      { label: "Property type", value: "Desert lodge — Soléi-owned" },
      { label: "Location", value: "Great Sand Sea · 1 hour from Siwa" },
      { label: "Total rooms", value: "3 desert suites" },
      { label: "Architecture", value: "Clay & palm-wood, low-built" },
      { label: "Power", value: "Solar · oil lamps after sunset" },
      { label: "Meals", value: "Full board · fire-cooked dinner" },
      { label: "Check-in", value: "From 3:00 PM (transfer included)" },
      { label: "Check-out", value: "By 10:00 AM" },
      { label: "Min. stay", value: "2 nights" },
    ],
    amenities: [
      "Star-gazing deck with telescope",
      "Fire pit & evening tea ritual",
      "Private desert guide on request",
      "Sandboarding & 4×4 excursions",
      "Full board (breakfast, lunch, dinner)",
      "Round-trip transfer from Siwa town",
      "Solar-powered hot water",
      "Outdoor desert shower",
      "Library of desert literature",
    ],
    rooms: [
      {
        name: "Desert Suite",
        type: "Suite · Dune-facing",
        desc: "A single-room suite opening directly onto the dunes, with a hand-built clay bed platform and a private outdoor terrace.",
        sqm: "~32 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 240,
      },
      {
        name: "Salt Flat Suite",
        type: "Suite · Lake-facing",
        desc: "Slightly larger, with a window arrangement positioned to catch the salt flat at sunrise. The most photographed room in the lodge.",
        sqm: "~38 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 290,
      },
      {
        name: "Family Tent Suite",
        type: "Suite · Private cluster",
        desc: "A twin-bedroom suite under a heavy canvas roof, suited to a family or two friends travelling together. Shared sitting area between the bedrooms.",
        sqm: "~52 m²",
        beds: "King bed + twin beds",
        occupancy: "Up to 4 guests",
        price: 380,
      },
    ],
    location: [
      { label: "From Siwa town", value: "~1 hour by 4×4 (transfer included)" },
      { label: "From Cairo", value: "~9 hours by private vehicle" },
      { label: "From Marsa Matrouh", value: "~4 hours by private 4×4" },
      { label: "Transfer arranged by", value: "Soléi (round trip from Siwa)" },
    ],
    reviews: [
      {
        name: "Hana & Pierre L.",
        origin: "France · Stayed November 2024",
        text: "Three nights and we still talk about it. Dinner under the stars was extraordinary, and the silence is something we are not used to anymore.",
      },
      {
        name: "Sara K.",
        origin: "Egypt · Stayed February 2025",
        text: "The team felt like family by the second day. Worth every minute of the drive — and the drive itself was beautiful.",
      },
    ],
    gallerySize: 12,
    related: ["solei-old-town", "solei-royal", "adrere-amellal"],
    basePrice: 240,
    priceLabel: "/ night · full board",
  },

  "solei-salt-caves": {
    slug: "solei-salt-caves",
    destination: "siwa-oasis",
    name: "Soléi Salt Caves",
    nameMain: "Soléi",
    nameItalic: "Salt Caves.",
    tagLine: "Wellness Retreat · Natural Caves · Ancient Healing",
    heroTag: "Soléi Owned · Wellness Retreat · Cave rooms",
    heroMeta: ["Siwa Oasis, Egypt", "Salt cave rooms", "Wellness retreat", "From €175 / night"],
    breadcrumbLabel: "Soléi Salt Caves",
    gradient: "bg-[linear-gradient(155deg,#162030_0%,#0a1828_45%,#1a2e40_100%)]",
    eyebrow: "Soléi Owned",
    headline: "A retreat carved into",
    headlineItalic: "Siwa's natural salt caves.",
    intro: [
      "Soléi Salt Caves is built around a cluster of natural salt caves on the western edge of the oasis — a microclimate locals have used for centuries to ease respiratory and skin conditions. The cave rooms are cool, quiet, and held at a constant humidity that does something to the way you sleep. Wake up, walk the salt path before breakfast, sit in the cave for an hour, repeat.",
      "This is one of our own properties. The wellness program is run by a local healer whose family has practised salt-cave therapy for three generations. Everything is unhurried, deliberate, and built around the caves themselves.",
    ],
    facts: [
      { label: "Property type", value: "Wellness retreat — Soléi-owned" },
      { label: "Location", value: "Western edge of Siwa Oasis" },
      { label: "Total rooms", value: "8 cave & garden rooms" },
      { label: "Architecture", value: "Natural salt cave + clay extension" },
      { label: "Wellness", value: "Daily salt-cave therapy session" },
      { label: "Meals", value: "Half board · plant-forward menu" },
      { label: "Check-in", value: "From 2:00 PM" },
      { label: "Check-out", value: "By 11:00 AM" },
      { label: "Min. stay", value: "2 nights" },
    ],
    amenities: [
      "Daily salt-cave therapy (60 min)",
      "Local healer-led wellness program",
      "Salt water plunge pool",
      "Yoga & breathwork sessions",
      "Half board (breakfast & dinner)",
      "Outdoor garden meditation deck",
      "Massage & body treatments on request",
      "Bicycles for oasis exploration",
      "Airport transfer arranged",
    ],
    rooms: [
      {
        name: "Cave Room",
        type: "Standard · Inside the salt cave",
        desc: "A room carved into the salt rock itself — cool year-round, lit gently, and held at a constant humidity. The defining experience of the property.",
        sqm: "~24 m²",
        beds: "Queen bed",
        occupancy: "Up to 2 guests",
        price: 175,
      },
      {
        name: "Garden Cave Suite",
        type: "Suite · Cave + private terrace",
        desc: "A larger cave room with a private clay terrace opening onto the herb garden. Best for guests doing a longer wellness program.",
        sqm: "~36 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 240,
      },
      {
        name: "Above-Cave Room",
        type: "Standard · Garden-facing",
        desc: "For guests who prefer windows and natural light — a clay-walled room above the cave network with views over the herb garden and salt path.",
        sqm: "~26 m²",
        beds: "Queen bed",
        occupancy: "Up to 2 guests",
        price: 195,
      },
    ],
    location: [
      { label: "From Siwa town centre", value: "~10 min by car or bicycle" },
      { label: "From Cairo", value: "~9 hours by private vehicle" },
      { label: "Cleopatra Spring", value: "~15 min by car" },
      { label: "Transfer arranged by", value: "Soléi" },
    ],
    reviews: [
      {
        name: "Mona T.",
        origin: "UAE · Stayed January 2025",
        text: "The cave room was unlike anywhere I've stayed. Slept deeper than I have in years and left feeling genuinely reset.",
      },
      {
        name: "James & Eloise B.",
        origin: "UK · Stayed March 2025",
        text: "Came for two nights, stayed five. The healer's program is the real thing — quiet, careful, and very effective.",
      },
    ],
    gallerySize: 11,
    related: ["solei-old-town", "solei-royal", "ghaliet-ecolodge-spa"],
    basePrice: 175,
    priceLabel: "/ night · half board",
  },

  "siwa-shali-resort": {
    slug: "siwa-shali-resort",
    destination: "siwa-oasis",
    name: "Siwa Shali Resort",
    nameMain: "Siwa Shali",
    nameItalic: "Resort.",
    tagLine: "Classic Resort · Since 2004 · Pool & Gardens",
    heroTag: "Resort · Old-city adjacent · Family-friendly",
    heroMeta: ["Siwa Oasis, Egypt", "Old city edge", "88 rooms", "From €110 / night"],
    breadcrumbLabel: "Siwa Shali Resort",
    gradient: "bg-[linear-gradient(155deg,#162d3e_0%,#1a3a52_60%,#0F2436_100%)]",
    eyebrow: "The property",
    headline: "A classic desert resort",
    headlineItalic: "since 2004.",
    intro: [
      "Siwa Shali Resort has been operating since 2004 — the most reliable choice in the oasis for guests who want amenities alongside the experience. Traditional Siwan architecture, palm-shaded gardens, and a pool that's particularly welcome in the afternoons.",
      "The resort hosts animation and cultural activities for families, and it's walking distance from the old city. Not the quietest option on the list, and deliberately so — this is a property built around people enjoying their holiday together.",
    ],
    facts: [
      { label: "Property type", value: "Resort" },
      { label: "Location", value: "Old city edge, Siwa" },
      { label: "Total rooms", value: "88 rooms" },
      { label: "Pool", value: "Outdoor freshwater pool" },
      { label: "Family", value: "Kids animation available" },
      { label: "Meals", value: "Half or full board" },
      { label: "Check-in", value: "From 2:00 PM" },
      { label: "Check-out", value: "By 12:00 PM" },
      { label: "Min. stay", value: "1 night" },
    ],
    amenities: [
      "Outdoor swimming pool",
      "Palm-shaded gardens",
      "Kids club & animation",
      "Restaurant on site",
      "Bar & lounge",
      "Bicycles available",
      "24-hour reception",
      "Airport transfer on request",
      "Near Shali ruins",
    ],
    rooms: [
      {
        name: "Standard Room",
        type: "Garden view",
        desc: "A comfortable standard room overlooking the gardens. Ideal for shorter stays or families using the resort as a base for day trips around the oasis.",
        sqm: "~24 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 110,
      },
      {
        name: "Family Room",
        type: "Garden · 2 connected rooms",
        desc: "Two connecting rooms that accommodate a family of four comfortably. Pool access and garden path walk.",
        sqm: "~42 m²",
        beds: "King + 2 singles",
        occupancy: "Up to 4 guests",
        price: 165,
      },
    ],
    location: [
      { label: "From Cairo", value: "~8 hours by private vehicle" },
      { label: "From Marsa Matrouh", value: "~3 hours by private 4×4" },
      { label: "Shali fortress", value: "5-minute walk" },
      { label: "Transfer arranged by", value: "Soléi or hotel" },
    ],
    reviews: [
      {
        name: "The Naim family",
        origin: "Egypt · Stayed August 2024",
        text: "Kids loved the pool, we loved the garden, and everyone slept well. Easy base for seeing everything in Siwa without committing to an eco-lodge rhythm.",
      },
      {
        name: "Chloé D.",
        origin: "France · Stayed October 2024",
        text: "Good value and a reliable team. Not boutique — but not trying to be. Exactly what we needed for a family week.",
      },
    ],
    gallerySize: 10,
    related: ["solei-old-town", "azad-siwa-hotel", "talist-siwa"],
    basePrice: 110,
    priceLabel: "/ night",
  },

  "ghaliet-ecolodge-spa": {
    slug: "ghaliet-ecolodge-spa",
    destination: "siwa-oasis",
    name: "Ghaliet Eco-Lodge & Spa",
    nameMain: "Ghaliet",
    nameItalic: "Eco-Lodge & Spa.",
    tagLine: "Wellness Sanctuary · Panoramic Pool · Spa",
    heroTag: "Eco Lodge · Spa · Desert panorama",
    heroMeta: ["Siwa Oasis, Egypt", "Desert edge", "22 rooms", "From €160 / night"],
    breadcrumbLabel: "Ghaliet Eco-Lodge & Spa",
    gradient: "bg-[linear-gradient(155deg,#0F2436_0%,#163040_60%,#1a3a52_100%)]",
    eyebrow: "The property",
    headline: "A five-star eco-lodge built",
    headlineItalic: "around wellness.",
    intro: [
      "Ghaliet is a desert wellness retreat — a panoramic pool overlooking the dunes, traditional Siwan design throughout, and a full spa programme rooted in local healing traditions. Salt baths, sand treatments, herbal wraps. The only lodge in Siwa where rest feels like an active choice rather than a default.",
      "The property is set slightly apart from the oasis centre, which makes the quiet in the afternoons genuinely quiet. Guests tend to arrive tired and leave differently.",
    ],
    facts: [
      { label: "Property type", value: "Eco-lodge with spa" },
      { label: "Location", value: "Desert edge, Siwa" },
      { label: "Total rooms", value: "22 rooms & suites" },
      { label: "Pool", value: "Panoramic infinity pool" },
      { label: "Spa", value: "Full programme · local rituals" },
      { label: "Meals", value: "Half or full board" },
      { label: "Check-in", value: "From 2:00 PM" },
      { label: "Check-out", value: "By 11:00 AM" },
      { label: "Min. stay", value: "2 nights" },
    ],
    amenities: [
      "Panoramic infinity pool",
      "Traditional Siwan spa",
      "Salt bath treatments",
      "Sand healing sessions",
      "Yoga pavilion",
      "Organic kitchen",
      "Desert stargazing deck",
      "Private excursions on request",
      "Airport transfer available",
    ],
    rooms: [
      {
        name: "Desert Room",
        type: "Standard · Dune view",
        desc: "A ground-floor room facing the dunes, cool interiors, warm textiles. Direct access to the spa wing.",
        sqm: "~28 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 160,
      },
      {
        name: "Pool View Suite",
        type: "Suite · Infinity pool view",
        desc: "A generous suite overlooking the infinity pool. Private terrace, outdoor shower, and uninterrupted desert horizon.",
        sqm: "~48 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 240,
      },
    ],
    location: [
      { label: "From Cairo", value: "~8 hours by private vehicle" },
      { label: "From Marsa Matrouh", value: "~3 hours by private 4×4" },
      { label: "From Siwa town centre", value: "~18 minutes" },
      { label: "Transfer arranged by", value: "Soléi or hotel" },
    ],
    reviews: [
      {
        name: "Hana F.",
        origin: "Jordan · Stayed February 2025",
        text: "I've done spas in the Alps and in Thailand. The salt bath at Ghaliet was more memorable than either. The silence in the spa wing is the luxury.",
      },
      {
        name: "Paul & Emma T.",
        origin: "Australia · Stayed November 2024",
        text: "We came for three nights and left feeling like we'd been on retreat for a fortnight. The pool at sunrise is worth setting an alarm for.",
      },
    ],
    gallerySize: 12,
    related: ["adrere-amellal", "taziry-ecolodge", "talist-siwa"],
    basePrice: 160,
    priceLabel: "/ night",
  },

  "talist-siwa": {
    slug: "talist-siwa",
    destination: "siwa-oasis",
    name: "Talist Siwa",
    nameMain: "Talist",
    nameItalic: "Siwa.",
    tagLine: "Family-Run Eco Lodge · Lake Views · Solar",
    heroTag: "Eco Lodge · Family-run · 100% solar",
    heroMeta: ["Siwa Oasis, Egypt", "Lake edge", "14 rooms & chalets", "From €130 / night"],
    breadcrumbLabel: "Talist Siwa",
    gradient: "bg-[linear-gradient(155deg,#1a3850_0%,#0F2436_60%,#162a3c_100%)]",
    eyebrow: "The property",
    headline: "A lodge run by the family",
    headlineItalic: "who built it.",
    intro: [
      "Talist is husband-and-wife-built — garden bungalows, lakeside chalets, and family suites, all designed around the natural springs that feed the land. One hundred percent solar. The care that comes from people who live on the property.",
      "Best for guests who want the quiet of an eco-lodge without the intensity of Adrère Amellal's no-electricity rule. Simple, warm, hosted.",
    ],
    facts: [
      { label: "Property type", value: "Family-run eco-lodge" },
      { label: "Location", value: "Lake edge, Siwa" },
      { label: "Total rooms", value: "14 rooms & chalets" },
      { label: "Power", value: "100% solar" },
      { label: "Natural springs", value: "On property" },
      { label: "Meals", value: "Breakfast included" },
      { label: "Check-in", value: "From 2:00 PM" },
      { label: "Check-out", value: "By 11:00 AM" },
      { label: "Min. stay", value: "1 night" },
    ],
    amenities: [
      "Natural spring access",
      "Solar-powered throughout",
      "Family-run kitchen",
      "Lake-view chalets",
      "Garden bungalows",
      "Bicycles available",
      "Local cuisine · vegetarian options",
      "Star-gazing deck",
      "Airport transfer arranged",
    ],
    rooms: [
      {
        name: "Garden Bungalow",
        type: "Standard · Palm garden",
        desc: "A small bungalow among the date palms, simple, calm, and close to the natural spring.",
        sqm: "~24 m²",
        beds: "Queen or twin",
        occupancy: "Up to 2 guests",
        price: 130,
      },
      {
        name: "Lakeside Chalet",
        type: "Superior · Lake view",
        desc: "A chalet with a private terrace facing the lake. Bigger, brighter, and the best position on the property.",
        sqm: "~34 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 190,
      },
      {
        name: "Family Suite",
        type: "Suite · 2 rooms",
        desc: "A two-bedroom suite with a shared sitting area, ideal for families of four.",
        sqm: "~50 m²",
        beds: "1 king + 2 singles",
        occupancy: "Up to 4 guests",
        price: 250,
      },
    ],
    location: [
      { label: "From Cairo", value: "~8 hours by private vehicle" },
      { label: "From Marsa Matrouh", value: "~3 hours by private 4×4" },
      { label: "From Siwa town centre", value: "~12 minutes" },
      { label: "Transfer arranged by", value: "Soléi or hotel" },
    ],
    reviews: [
      {
        name: "Tobias R.",
        origin: "Netherlands · Stayed March 2025",
        text: "The owners remembered our names and our son's dietary preferences on the first morning. Everything we ate came from their garden or a neighbour's. This is what hospitality used to mean.",
      },
      {
        name: "Nadia E.",
        origin: "Egypt · Stayed January 2025",
        text: "Small, calm, perfect for a quiet weekend. The natural spring is cold in the best way.",
      },
    ],
    gallerySize: 10,
    related: ["taziry-ecolodge", "ghaliet-ecolodge-spa", "azad-siwa-hotel"],
    basePrice: 130,
    priceLabel: "/ night",
  },

  "azad-siwa-hotel": {
    slug: "azad-siwa-hotel",
    destination: "siwa-oasis",
    name: "Azad Siwa Hotel",
    nameMain: "Azad Siwa",
    nameItalic: "Hotel.",
    tagLine: "Boutique Hotel · Salt-Brick · Near Oracle Temple",
    heroTag: "Boutique · 9.4 rated · Near Oracle Temple",
    heroMeta: ["Siwa Oasis, Egypt", "Central Siwa", "18 rooms", "From €95 / night"],
    breadcrumbLabel: "Azad Siwa Hotel",
    gradient: "bg-[linear-gradient(155deg,#1a3a52_0%,#152c3e_60%,#0F2436_100%)]",
    eyebrow: "The property",
    headline: "The highest-rated boutique",
    headlineItalic: "hotel in the oasis.",
    intro: [
      "Azad Siwa Hotel is the highest-rated property in the oasis — authentic Siwan salt-brick architecture, Chef Ibrahim's local cuisine, and a prime location moments from the Oracle Temple and Cleopatra's Bath. Central, walkable, and consistently praised for the quality of the kitchen.",
      "Not a luxury resort, but a genuinely well-run boutique hotel. The best value on our list when you account for location and food.",
    ],
    facts: [
      { label: "Property type", value: "Boutique hotel" },
      { label: "Location", value: "Central Siwa" },
      { label: "Total rooms", value: "18 rooms" },
      { label: "Guest rating", value: "9.4 / 10" },
      { label: "Kitchen", value: "Chef-led Siwan cuisine" },
      { label: "Meals", value: "Breakfast included" },
      { label: "Check-in", value: "From 2:00 PM" },
      { label: "Check-out", value: "By 11:00 AM" },
      { label: "Min. stay", value: "1 night" },
    ],
    amenities: [
      "Chef-led Siwan kitchen",
      "Rooftop restaurant",
      "Walking access to Oracle Temple",
      "Walking access to Cleopatra's Bath",
      "Local cuisine · vegetarian options",
      "Bicycles available",
      "Cultural tours arranged",
      "24-hour reception",
      "Airport transfer on request",
    ],
    rooms: [
      {
        name: "Salt-Brick Room",
        type: "Standard · Central",
        desc: "A traditional salt-brick room in the heart of the hotel. Warm, simple, well-maintained.",
        sqm: "~22 m²",
        beds: "Queen bed",
        occupancy: "Up to 2 guests",
        price: 95,
      },
      {
        name: "Rooftop Room",
        type: "Superior · Village views",
        desc: "A higher room with access to the rooftop restaurant and open views across central Siwa.",
        sqm: "~28 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 140,
      },
    ],
    location: [
      { label: "From Cairo", value: "~8 hours by private vehicle" },
      { label: "From Marsa Matrouh", value: "~3 hours by private 4×4" },
      { label: "Oracle Temple", value: "10-minute walk" },
      { label: "Transfer arranged by", value: "Soléi or hotel" },
    ],
    reviews: [
      {
        name: "David S.",
        origin: "USA · Stayed December 2024",
        text: "Best value in Siwa. Clean, central, and the rooftop dinner was a genuine highlight. We'd stay again tomorrow.",
      },
      {
        name: "Ines P.",
        origin: "Portugal · Stayed October 2024",
        text: "The team at Azad are the reason the guest rating is so high. Everyone was helpful without performing it.",
      },
    ],
    gallerySize: 8,
    related: ["solei-old-town", "siwa-shali-resort", "talist-siwa"],
    basePrice: 95,
    priceLabel: "/ night",
  },

  // ─── NORTH COAST ────────────────────────────────────────────

  "address-beach-resort-marassi": {
    slug: "address-beach-resort-marassi",
    destination: "north-coast",
    name: "Address Beach Resort Marassi",
    nameMain: "Address Beach",
    nameItalic: "Marassi.",
    tagLine: "Luxury Resort · Marassi · Direct beach access",
    heroTag: "Flagship Property · Mediterranean front · Enquire to book",
    heroMeta: ["North Coast, Egypt", "Marassi", "Private beach", "From €290 / night"],
    breadcrumbLabel: "Address Beach Resort Marassi",
    gradient: "bg-[linear-gradient(155deg,#1a4a6a_0%,#0F2436_100%)]",
    eyebrow: "The property",
    headline: "The Address brand's most",
    headlineItalic: "refined coastal expression.",
    intro: [
      "Address Beach Resort Marassi is a luxury beachfront property offering rooms and suites with beach-to-lagoon views, world-class amenities, and direct Mediterranean access. Rooms face the sea. Evenings here are genuinely still.",
      "The flagship of our North Coast list — scaled for guests who want a full resort experience without sacrificing the quiet. Private beach, multiple pool zones, and a level of service that understands the difference between attentive and intrusive.",
    ],
    facts: [
      { label: "Property type", value: "Luxury beach resort" },
      { label: "Location", value: "Marassi · Mediterranean front" },
      { label: "Total rooms", value: "200+ rooms & suites" },
      { label: "Beach", value: "Private · direct access" },
      { label: "Pools", value: "Multiple zones" },
      { label: "Meals", value: "Multiple restaurants" },
      { label: "Check-in", value: "From 3:00 PM" },
      { label: "Check-out", value: "By 12:00 PM" },
      { label: "Min. stay", value: "2 nights" },
    ],
    amenities: [
      "Private beach",
      "Multiple pool zones",
      "Sea-facing rooms",
      "Fine dining restaurants",
      "Full spa & wellness",
      "Kids club",
      "24-hour room service",
      "Fitness centre",
      "Private transfers arranged",
    ],
    rooms: [
      {
        name: "Deluxe Room",
        type: "Standard · Lagoon view",
        desc: "Generous contemporary room overlooking the lagoon or gardens. King or twin beds, full marble bathroom, private balcony.",
        sqm: "~45 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 290,
      },
      {
        name: "Sea View Suite",
        type: "Superior · Direct sea view",
        desc: "A larger suite with an uninterrupted Mediterranean view and a private balcony positioned for sunset. Separate sitting area.",
        sqm: "~70 m²",
        beds: "King bed",
        occupancy: "Up to 3 guests",
        price: 420,
      },
      {
        name: "Beachfront Suite",
        type: "Suite · Beach-level · Private terrace",
        desc: "Beach-level suite with a terrace that opens directly onto the sand. The most immediate sea access on the property.",
        sqm: "~110 m²",
        beds: "King bed",
        occupancy: "Up to 4 guests",
        price: 640,
      },
    ],
    location: [
      { label: "From Cairo", value: "~2.5 hours by private vehicle" },
      { label: "From Alexandria", value: "~45 min–1 hour by private vehicle" },
      { label: "Marassi Marina", value: "5-minute drive" },
      { label: "Transfer arranged by", value: "Soléi — private vehicle" },
    ],
    reviews: [
      {
        name: "The Rahman family",
        origin: "UAE · Stayed August 2024",
        text: "Exactly what the Address name promises — and on this stretch of Mediterranean it finally has the setting to live up to it. Service was quietly excellent.",
      },
      {
        name: "Victor & Elena M.",
        origin: "Spain · Stayed September 2024",
        text: "The beach is genuinely beautiful, the suite was the size of our Madrid apartment, and the staff treated us like neighbours rather than guests. We'll be back in May.",
      },
    ],
    gallerySize: 18,
    related: [
      "vida-marina-resort-marassi",
      "address-marassi-golf-resort",
      "casa-cook-north-coast",
    ],
    basePrice: 290,
    priceLabel: "/ night",
  },

  "vida-marina-resort-marassi": {
    slug: "vida-marina-resort-marassi",
    destination: "north-coast",
    name: "Vida Marina Resort Marassi",
    nameMain: "Vida Marina",
    nameItalic: "Marassi.",
    tagLine: "Luxury Resort · Marassi Marina · Mediterranean front",
    heroTag: "Marina · Sea views · Enquire to book",
    heroMeta: ["North Coast, Egypt", "Marassi Marina", "Sea-view rooms", "From €210 / night"],
    breadcrumbLabel: "Vida Marina Resort Marassi",
    gradient: "bg-[linear-gradient(155deg,#2F6F8F_0%,#1a4a6a_100%)]",
    eyebrow: "The property",
    headline: "Upscale marina living",
    headlineItalic: "on the Mediterranean.",
    intro: [
      "Vida Marina Resort is positioned on Marassi's marina, with uninterrupted sea views from almost every room. Contemporary design, generous common spaces, and a restaurant that makes the most of the coastal setting.",
      "The most social of the Marassi properties — best for guests who want proximity to activity without being inside it. Lively in the evenings, composed in the mornings.",
    ],
    facts: [
      { label: "Property type", value: "Luxury resort" },
      { label: "Location", value: "Marassi Marina" },
      { label: "Total rooms", value: "160 rooms & suites" },
      { label: "Pool", value: "Rooftop + marina-front" },
      { label: "Beach", value: "Short walk to private beach" },
      { label: "Meals", value: "Breakfast · restaurants" },
      { label: "Check-in", value: "From 3:00 PM" },
      { label: "Check-out", value: "By 12:00 PM" },
      { label: "Min. stay", value: "2 nights" },
    ],
    amenities: [
      "Marina views",
      "Rooftop pool",
      "Beach access",
      "Water sports centre",
      "Multiple restaurants",
      "Fitness & spa",
      "24-hour reception",
      "Complimentary mini-bar",
      "Private transfers arranged",
    ],
    rooms: [
      {
        name: "Superior Room",
        type: "Marina view",
        desc: "Contemporary room with a private balcony overlooking the marina. Complimentary mini-bar and full marble bathroom.",
        sqm: "~36 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 210,
      },
      {
        name: "Marina Suite",
        type: "Superior · 1-bedroom suite",
        desc: "A one-bedroom suite with a separate living area and a larger balcony facing both the marina and the sea.",
        sqm: "~62 m²",
        beds: "King bed",
        occupancy: "Up to 3 guests",
        price: 310,
      },
    ],
    location: [
      { label: "From Cairo", value: "~2.5 hours by private vehicle" },
      { label: "From Alexandria", value: "~1 hour by private vehicle" },
      { label: "Marassi Marina", value: "On property" },
      { label: "Transfer arranged by", value: "Soléi — private vehicle" },
    ],
    reviews: [
      {
        name: "Kareem & Lara B.",
        origin: "Lebanon · Stayed July 2024",
        text: "Great position — we walked to dinner most nights. The marina view at sunset is the best thing about Marassi and this property sits right on top of it.",
      },
      {
        name: "The Sharif family",
        origin: "Egypt · Stayed August 2024",
        text: "Reliable, comfortable, and the kids were happy in the pool. The staff remembered us on the second morning, which goes a long way at a big property.",
      },
    ],
    gallerySize: 13,
    related: [
      "address-beach-resort-marassi",
      "address-marassi-golf-resort",
      "casa-cook-north-coast",
    ],
    basePrice: 210,
    priceLabel: "/ night",
  },

  "address-marassi-golf-resort": {
    slug: "address-marassi-golf-resort",
    destination: "north-coast",
    name: "Address Marassi Golf Resort",
    nameMain: "Address Marassi",
    nameItalic: "Golf Resort.",
    tagLine: "Golf Resort · Marassi · 18-hole course",
    heroTag: "Golf · Sea views · Enquire to book",
    heroMeta: ["North Coast, Egypt", "Marassi", "18-hole course", "From €240 / night"],
    breadcrumbLabel: "Address Marassi Golf Resort",
    gradient: "bg-[linear-gradient(155deg,#2F6F8F_0%,#1a3a52_100%)]",
    eyebrow: "The property",
    headline: "Eighteen holes with the",
    headlineItalic: "Mediterranean as a backdrop.",
    intro: [
      "Address Marassi Golf Resort offers championship course views, deluxe to suite accommodations, and premium golf amenities. Rooms overlook either the fairways or the sea — both are worth waking up to.",
      "A quieter, more composed option than the beach-front properties. Suited to guests who want to play in the morning and rest properly in the afternoon. Also a genuinely good choice for non-golfers who value space.",
    ],
    facts: [
      { label: "Property type", value: "Golf resort" },
      { label: "Location", value: "Marassi · golf course" },
      { label: "Total rooms", value: "120 rooms & suites" },
      { label: "Course", value: "18 holes · championship" },
      { label: "Pools", value: "3 pool zones" },
      { label: "Meals", value: "Clubhouse + restaurants" },
      { label: "Check-in", value: "From 3:00 PM" },
      { label: "Check-out", value: "By 12:00 PM" },
      { label: "Min. stay", value: "2 nights" },
    ],
    amenities: [
      "18-hole championship course",
      "Sea-view rooms available",
      "Clubhouse dining",
      "Multiple pool zones",
      "Spa access",
      "Tennis courts",
      "Beach access via shuttle",
      "Golf lessons on request",
      "Private transfers arranged",
    ],
    rooms: [
      {
        name: "Deluxe Room",
        type: "Standard · Fairway view",
        desc: "A deluxe room overlooking the fairways, with a private balcony and walking access to the clubhouse.",
        sqm: "~42 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 240,
      },
      {
        name: "Sea View Suite",
        type: "Suite · Mediterranean view",
        desc: "A suite with uninterrupted sea views and a larger balcony. Separate living area.",
        sqm: "~72 m²",
        beds: "King bed",
        occupancy: "Up to 3 guests",
        price: 380,
      },
    ],
    location: [
      { label: "From Cairo", value: "~2.5 hours by private vehicle" },
      { label: "From Alexandria", value: "~1 hour by private vehicle" },
      { label: "Marassi Marina", value: "10-minute drive" },
      { label: "Transfer arranged by", value: "Soléi — private vehicle" },
    ],
    reviews: [
      {
        name: "Ahmed T.",
        origin: "Egypt · Stayed May 2024",
        text: "Played the course three mornings in a row and the last afternoon went to the beach. Everything about this stay was simple and well-executed.",
      },
      {
        name: "Sarah & Rob M.",
        origin: "United Kingdom · Stayed October 2024",
        text: "Neither of us plays golf — we booked for the sea view rooms and the space. Best decision of the holiday. The pool zones are perfect for reading.",
      },
    ],
    gallerySize: 12,
    related: [
      "address-beach-resort-marassi",
      "vida-marina-resort-marassi",
      "casa-cook-north-coast",
    ],
    basePrice: 240,
    priceLabel: "/ night",
  },

  "casa-cook-north-coast": {
    slug: "casa-cook-north-coast",
    destination: "north-coast",
    name: "Casa Cook North Coast",
    nameMain: "Casa Cook",
    nameItalic: "North Coast.",
    tagLine: "Boutique Resort · Design hotel · Beachfront",
    heroTag: "Boutique · Design-led · Enquire to book",
    heroMeta: ["North Coast, Egypt", "Design hotel", "Beachfront", "From €195 / night"],
    breadcrumbLabel: "Casa Cook North Coast",
    gradient: "bg-[linear-gradient(155deg,#235570_0%,#2F6F8F_100%)]",
    eyebrow: "The property",
    headline: "Minimalist beachfront luxury,",
    headlineItalic: "done properly.",
    intro: [
      "Casa Cook's signature design — earthy tones, rattan, organic forms — works unusually well against the Egyptian coastal landscape. For guests who travel slowly and notice the details most resorts overlook.",
      "Smaller, quieter, more considered than the surrounding developments. Adults-friendly by design, and consistently praised as the most characterful stay on this part of the coast.",
    ],
    facts: [
      { label: "Property type", value: "Boutique resort" },
      { label: "Location", value: "North Coast · beachfront" },
      { label: "Total rooms", value: "80 rooms" },
      { label: "Design", value: "Casa Cook signature" },
      { label: "Audience", value: "Adults-friendly" },
      { label: "Meals", value: "Breakfast · beach club" },
      { label: "Check-in", value: "From 3:00 PM" },
      { label: "Check-out", value: "By 12:00 PM" },
      { label: "Min. stay", value: "2 nights" },
    ],
    amenities: [
      "Design-led rooms",
      "Beach club on site",
      "Yoga & wellness programme",
      "Adults-friendly atmosphere",
      "Pool & beachfront",
      "Mediterranean menu",
      "Cocktail bar",
      "Bicycles available",
      "Private transfers arranged",
    ],
    rooms: [
      {
        name: "Garden Room",
        type: "Standard · Casa Cook design",
        desc: "A warm, considered room in the Casa Cook signature — earthy palette, natural textiles, private outdoor terrace.",
        sqm: "~32 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 195,
      },
      {
        name: "Beach Suite",
        type: "Suite · Sea-facing terrace",
        desc: "A larger suite with a terrace that opens onto the beach path. Outdoor shower, larger living area.",
        sqm: "~54 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 305,
      },
    ],
    location: [
      { label: "From Cairo", value: "~2.5 hours by private vehicle" },
      { label: "From Alexandria", value: "~1 hour by private vehicle" },
      { label: "Marassi", value: "15-minute drive" },
      { label: "Transfer arranged by", value: "Soléi — private vehicle" },
    ],
    reviews: [
      {
        name: "Maria C.",
        origin: "Italy · Stayed September 2024",
        text: "We've stayed at Casa Cook in Greece and Ibiza. This one holds its own — which is saying something given the setting.",
      },
      {
        name: "Omar & Yara D.",
        origin: "Egypt · Stayed June 2024",
        text: "Smallest property we looked at. Best one we stayed in. You can tell someone designed each detail.",
      },
    ],
    gallerySize: 14,
    related: [
      "address-beach-resort-marassi",
      "the-g-hotel-seashell",
      "jaz-almaza-beach-resort",
    ],
    basePrice: 195,
    priceLabel: "/ night",
  },

  "jaz-almaza-beach-resort": {
    slug: "jaz-almaza-beach-resort",
    destination: "north-coast",
    name: "Jaz Almaza Beach Resort",
    nameMain: "Jaz Almaza",
    nameItalic: "Beach Resort.",
    tagLine: "Beach Resort · Almaza Bay · All-inclusive option",
    heroTag: "Almaza Bay · Beach · Enquire to book",
    heroMeta: ["North Coast, Egypt", "Almaza Bay", "Private beach", "From €175 / night"],
    breadcrumbLabel: "Jaz Almaza Beach Resort",
    gradient: "bg-[linear-gradient(155deg,#1d5070_0%,#0F2436_100%)]",
    eyebrow: "The property",
    headline: "On Almaza Bay's most",
    headlineItalic: "praised stretch of beach.",
    intro: [
      "Clear water, white sand, and a quality of light in the afternoons that photographers know about. Family-friendly with entertainment and all-inclusive available but not compulsory.",
      "Larger than Casa Cook but less frenetic than the Marassi cluster. A genuinely relaxing coastal choice — and arguably the best swimming on the North Coast.",
    ],
    facts: [
      { label: "Property type", value: "Beach resort" },
      { label: "Location", value: "Almaza Bay" },
      { label: "Total rooms", value: "250+ rooms" },
      { label: "Beach", value: "Private · crystal clear water" },
      { label: "Meals", value: "Half-board or all-inclusive" },
      { label: "Family", value: "Kids club & entertainment" },
      { label: "Check-in", value: "From 3:00 PM" },
      { label: "Check-out", value: "By 12:00 PM" },
      { label: "Min. stay", value: "2 nights" },
    ],
    amenities: [
      "Private beach",
      "Crystal-clear water",
      "Multiple restaurants",
      "Water sports centre",
      "Kids club",
      "All-inclusive option",
      "Pool zones",
      "Nightly entertainment",
      "Private transfers arranged",
    ],
    rooms: [
      {
        name: "Family Room",
        type: "Garden view",
        desc: "A family room accommodating four comfortably, with garden views and easy access to the kids club.",
        sqm: "~38 m²",
        beds: "King + 2 singles",
        occupancy: "Up to 4 guests",
        price: 175,
      },
      {
        name: "Sea View Room",
        type: "Superior · Beach-facing",
        desc: "A superior room with a private balcony facing the Mediterranean. Best for couples.",
        sqm: "~34 m²",
        beds: "King bed",
        occupancy: "Up to 2 guests",
        price: 235,
      },
    ],
    location: [
      { label: "From Cairo", value: "~3 hours by private vehicle" },
      { label: "From Alexandria", value: "~1.5 hours by private vehicle" },
      { label: "Marsa Matrouh Airport", value: "~1 hour by vehicle" },
      { label: "Transfer arranged by", value: "Soléi — private vehicle" },
    ],
    reviews: [
      {
        name: "The Yousef family",
        origin: "Egypt · Stayed July 2024",
        text: "The water at Almaza Bay is the best in Egypt. The resort knows it and doesn't get in the way of it.",
      },
      {
        name: "Lina N.",
        origin: "Germany · Stayed August 2024",
        text: "We chose half-board rather than all-inclusive and were glad — the local Alexandrian dinners we went out for were as much a highlight as the beach.",
      },
    ],
    gallerySize: 15,
    related: ["the-g-hotel-seashell", "casa-cook-north-coast", "rixos-premium-alamein"],
    basePrice: 175,
    priceLabel: "/ night",
  },

  "the-g-hotel-seashell": {
    slug: "the-g-hotel-seashell",
    destination: "north-coast",
    name: "The G Hotel Seashell",
    nameMain: "The G Hotel",
    nameItalic: "Seashell.",
    tagLine: "Boutique Hotel · Almaza Bay · Intimate",
    heroTag: "Boutique · Almaza Bay · Enquire to book",
    heroMeta: ["North Coast, Egypt", "Almaza Bay", "Villa options", "From €185 / night"],
    breadcrumbLabel: "The G Hotel Seashell",
    gradient: "bg-[linear-gradient(155deg,#163a52_0%,#2F6F8F_100%)]",
    eyebrow: "The property",
    headline: "One of Almaza Bay's",
    headlineItalic: "most intimate stays.",
    intro: [
      "The G Hotel Seashell offers a quieter alternative to the larger resort complexes on Almaza Bay — fewer rooms, more attention per guest, and direct beach access without the crowds. Villa options up to five bedrooms for families or small groups.",
      "Well suited to couples, solo travellers, and small families wanting a genuinely unhurried coastal stay. Not an all-inclusive — and deliberately so.",
    ],
    facts: [
      { label: "Property type", value: "Boutique beachfront hotel" },
      { label: "Location", value: "Almaza Bay" },
      { label: "Total rooms", value: "45 rooms + 6 villas" },
      { label: "Villa options", value: "Up to 5 bedrooms" },
      { label: "Beach", value: "Private · walking distance" },
      { label: "Meals", value: "Breakfast included" },
      { label: "Check-in", value: "From 3:00 PM" },
      { label: "Check-out", value: "By 12:00 PM" },
      { label: "Min. stay", value: "2 nights" },
    ],
    amenities: [
      "Intimate scale",
      "Private beach access",
      "Villa options available",
      "Personalised service",
      "Quiet location",
      "Pool & sun terraces",
      "Local cuisine kitchen",
      "Bicycles available",
      "Private transfers arranged",
    ],
    rooms: [
      {
        name: "Seashell Room",
        type: "Standard · Garden view",
        desc: "A quiet, well-appointed standard room with a private terrace opening onto the garden.",
        sqm: "~32 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 185,
      },
      {
        name: "5-Bedroom Villa",
        type: "Villa · Private · Sea access",
        desc: "An entire villa with five bedrooms, a private pool, and beach access. Priced per night for the whole villa.",
        sqm: "~380 m²",
        beds: "5 bedrooms · sleeps 10",
        occupancy: "Up to 10 guests",
        price: 890,
      },
    ],
    location: [
      { label: "From Cairo", value: "~3 hours by private vehicle" },
      { label: "From Alexandria", value: "~1.5 hours by private vehicle" },
      { label: "Almaza Bay beach", value: "2-minute walk" },
      { label: "Transfer arranged by", value: "Soléi — private vehicle" },
    ],
    reviews: [
      {
        name: "Pierre & Mathilde A.",
        origin: "France · Stayed September 2024",
        text: "We booked a villa for eight days. Smaller and quieter than we expected, in the best way. The beach was never crowded because the property simply isn't big enough for that.",
      },
      {
        name: "Khaled R.",
        origin: "Egypt · Stayed June 2024",
        text: "Best intimate option on the coast. Staff remembered our son's name, our dinner preferences, our reading choices. Rare at a beach hotel.",
      },
    ],
    gallerySize: 12,
    related: ["jaz-almaza-beach-resort", "casa-cook-north-coast", "al-alamein-hotel"],
    basePrice: 185,
    priceLabel: "/ night",
  },

  "rixos-premium-alamein": {
    slug: "rixos-premium-alamein",
    destination: "north-coast",
    name: "Rixos Premium Alamein",
    nameMain: "Rixos Premium",
    nameItalic: "Alamein.",
    tagLine: "Premium Resort · El Alamein · Ultra all-inclusive",
    heroTag: "Premium · All-inclusive · Enquire to book",
    heroMeta: ["North Coast, Egypt", "El Alamein", "Private beach", "From €260 / night"],
    breadcrumbLabel: "Rixos Premium Alamein",
    gradient: "bg-[linear-gradient(155deg,#1a3a52_0%,#2F6F8F_100%)]",
    eyebrow: "The property",
    headline: "Rixos's all-inclusive concept,",
    headlineItalic: "at its most comprehensive.",
    intro: [
      "Private beach, multiple restaurants and bars, entertainment, spa, and a genuinely expansive stretch of Mediterranean coast. Particularly suited to families or guests who want everything on site — the largest property in our North Coast portfolio, and the most self-contained.",
      "The all-inclusive here is unusually comprehensive without feeling processed. The food, the service, the infrastructure all earn the 'premium' in the name.",
    ],
    facts: [
      { label: "Property type", value: "Premium all-inclusive resort" },
      { label: "Location", value: "El Alamein" },
      { label: "Total rooms", value: "350+ rooms & suites" },
      { label: "Beach", value: "Private · expansive" },
      { label: "Meals", value: "Ultra all-inclusive" },
      { label: "Family", value: "Kids waterpark + clubs" },
      { label: "Check-in", value: "From 3:00 PM" },
      { label: "Check-out", value: "By 12:00 PM" },
      { label: "Min. stay", value: "3 nights" },
    ],
    amenities: [
      "Ultra all-inclusive",
      "Private beach",
      "5+ restaurants",
      "Premium spa",
      "Kids waterpark",
      "Multiple pool zones",
      "Evening entertainment",
      "Club amenities",
      "Private transfers arranged",
    ],
    rooms: [
      {
        name: "Deluxe Room",
        type: "Standard · Sea view",
        desc: "A deluxe room with Mediterranean views and a private balcony. All-inclusive covers all meals, drinks, and most activities.",
        sqm: "~42 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 260,
      },
      {
        name: "Club Suite",
        type: "Suite · Club access",
        desc: "A larger suite with access to the adults-only club lounge, private bar, and concierge-level service.",
        sqm: "~75 m²",
        beds: "King bed",
        occupancy: "Up to 3 guests",
        price: 420,
      },
      {
        name: "Family Suite",
        type: "Suite · 2 bedrooms",
        desc: "A family suite with two connected bedrooms, a shared sitting room, and garden or pool access.",
        sqm: "~90 m²",
        beds: "King + 2 singles",
        occupancy: "Up to 5 guests",
        price: 520,
      },
    ],
    location: [
      { label: "From Cairo", value: "~2.5 hours by private vehicle" },
      { label: "From Alexandria", value: "~45 min by private vehicle" },
      { label: "WWII Museum", value: "15-minute drive" },
      { label: "Transfer arranged by", value: "Soléi — private vehicle" },
    ],
    reviews: [
      {
        name: "The Al-Shammari family",
        origin: "Kuwait · Stayed August 2024",
        text: "We are a family of eight. Every one of us found something they enjoyed. That is the bar for a resort like this — and Rixos cleared it.",
      },
      {
        name: "George N.",
        origin: "Greece · Stayed July 2024",
        text: "I am sceptical of all-inclusive on principle. This one changed my mind for a week. The food was good enough that I never once asked to go elsewhere.",
      },
    ],
    gallerySize: 17,
    related: ["al-alamein-hotel", "jaz-almaza-beach-resort", "address-beach-resort-marassi"],
    basePrice: 260,
    priceLabel: "/ night",
  },

  "al-alamein-hotel": {
    slug: "al-alamein-hotel",
    destination: "north-coast",
    name: "Al Alamein Hotel",
    nameMain: "Al Alamein",
    nameItalic: "Hotel.",
    tagLine: "Heritage Hotel · El Alamein · Sea front",
    heroTag: "Heritage · Coastal · Enquire to book",
    heroMeta: ["North Coast, Egypt", "El Alamein", "Sea-front position", "From €175 / night"],
    breadcrumbLabel: "Al Alamein Hotel",
    gradient: "bg-[linear-gradient(155deg,#0F2436_0%,#3d8aad_100%)]",
    eyebrow: "The property",
    headline: "A proper hotel with",
    headlineItalic: "character and history.",
    intro: [
      "Al Alamein Hotel is one of the original hotels on this stretch of coast — older, quieter, and carrying a faded grandeur that suits the historical weight of El Alamein. Not a luxury resort: a proper hotel with character, a sea-front position, and proximity to the WWII museum and cemetery that most coastal guests never visit.",
      "Best for travellers who want to understand this part of Egypt more fully — and to come back to a comfortable room at the end of the day.",
    ],
    facts: [
      { label: "Property type", value: "Heritage hotel" },
      { label: "Location", value: "El Alamein · sea front" },
      { label: "Total rooms", value: "80 rooms" },
      { label: "Setting", value: "Quiet · historical" },
      { label: "Beach", value: "Direct sea-front access" },
      { label: "Meals", value: "Breakfast · half-board option" },
      { label: "Check-in", value: "From 3:00 PM" },
      { label: "Check-out", value: "By 12:00 PM" },
      { label: "Min. stay", value: "1 night" },
    ],
    amenities: [
      "Sea-front position",
      "Heritage character",
      "Near WWII Museum & cemetery",
      "Quiet location",
      "Restaurant on site",
      "Private beach access",
      "Pool",
      "24-hour reception",
      "Private transfers arranged",
    ],
    rooms: [
      {
        name: "Superior Room",
        type: "Standard · Sea-front wing",
        desc: "A comfortable superior room in the sea-front wing with a private balcony overlooking the Mediterranean.",
        sqm: "~30 m²",
        beds: "King or twin",
        occupancy: "Up to 2 guests",
        price: 175,
      },
      {
        name: "Family Room",
        type: "Superior · Sea or garden view",
        desc: "A family-sized room accommodating four with sea or garden views.",
        sqm: "~45 m²",
        beds: "King + 2 singles",
        occupancy: "Up to 4 guests",
        price: 240,
      },
    ],
    location: [
      { label: "From Cairo", value: "~2.5 hours by private vehicle" },
      { label: "From Alexandria", value: "~1 hour by private vehicle" },
      { label: "WWII Museum", value: "10-minute walk" },
      { label: "Transfer arranged by", value: "Soléi — private vehicle" },
    ],
    reviews: [
      {
        name: "Henry B.",
        origin: "United Kingdom · Stayed May 2024",
        text: "We came specifically for the WWII sites. The hotel is old-fashioned in the right way — comfortable, respectful, and located precisely where you want to be.",
      },
      {
        name: "Nadia & Tarek F.",
        origin: "Egypt · Stayed April 2024",
        text: "Much quieter than Marassi, which was the point. We walked to the cemetery one morning and sat with our coffee afterwards — a day we'll remember.",
      },
    ],
    gallerySize: 9,
    related: ["rixos-premium-alamein", "jaz-almaza-beach-resort", "the-g-hotel-seashell"],
    basePrice: 175,
    priceLabel: "/ night",
  },
};

export function getHotelDetail(slug: string): HotelDetail | null {
  const canonical = canonicalHotelSlug(slug);
  return HOTEL_DETAILS[canonical] ?? null;
}

export { coastalGradient, siwaDestGradient };
