/**
 * Initial seed data for MemStorage hotels and blog posts.
 *
 * Each record holds the *thin* fields the admin dashboard surfaces
 * directly (name, slug, blurb, image, prices, destination, category,
 * amenities). The rich detail content (rooms, facts, reviews, hero
 * meta, etc.) lives in the optional `details` JSONB and stays null
 * here for now — the public detail pages still resolve those fields
 * from client/src/lib/hotel-data.ts and blog-data.ts as a fallback,
 * so nothing on the public site changes when this seed runs.
 *
 * Editing a record from the admin UI overwrites the in-memory copy
 * (and, once Postgres is attached, the row). Public pages will pick
 * up edits in Phase 1B when the data hooks are wired.
 */

import type { InsertHotel, InsertBlogPost, InsertExperience } from "@shared/schema";

type SeedHotel = Omit<InsertHotel, "amenities"> & { amenities: string[] };

export const seedHotels: SeedHotel[] = [
  // ─── Siwa ────────────────────────────────────────────────────
  {
    slug: "adrere-amellal",
    name: "Adrère Amellal",
    destination: "siwa",
    category: "Eco Lodge",
    blurb:
      "Egypt's most celebrated eco-lodge. Built entirely from karsheef salt rock and palm wood into the white mountain at the edge of the salt lake.",
    description:
      "No electricity, no internet, no noise — just the oasis in its most elemental form. Oil lamps at night.",
    pricePerNight: "€320 / night · full board",
    imageUrl: "/attached_assets/adrerre-amelal_1751755031600.jpg",
    amenities: ["Full board", "Salt lake access", "Oil lamp lighting", "Organic farm"],
    eco: true,
    luxury: true,
    isActive: true,
  },
  {
    slug: "taziry-ecolodge",
    name: "Taziry Ecolodge",
    destination: "siwa",
    category: "Boutique Eco Lodge",
    blurb:
      "Mud-brick villas around a courtyard garden, with uninterrupted views of Siwa's salt lakes and a salt water pool.",
    description: "Organic kitchen, unhurried service. More accessible than Adrère Amellal, no less considered.",
    pricePerNight: "€180 / night",
    imageUrl: "/attached_assets/taziry-room-.jpg",
    amenities: ["Salt water pool", "Lake views", "Organic kitchen", "Mud-brick villas"],
    eco: true,
    luxury: false,
    isActive: true,
  },
  {
    slug: "ghaliet-ecolodge-spa",
    name: "Ghaliet Ecolodge & Spa",
    destination: "siwa",
    category: "Eco Lodge · Spa",
    blurb:
      "Traditional Siwan mud architecture with a spa grounded in local healing knowledge — salt baths, sand treatments, herbal wraps.",
    description: "A natural salt pool filled from the oasis's own springs.",
    pricePerNight: "€160 / night",
    imageUrl: "/attached_assets/galit-lodge-siwa_1751833109925.jpg",
    amenities: ["Natural salt pool", "Traditional spa", "Sand treatments", "Healing rituals"],
    eco: true,
    luxury: false,
    isActive: true,
  },
  {
    slug: "talist-siwa",
    name: "Talist Siwa",
    destination: "siwa",
    category: "Boutique Hotel",
    blurb:
      "On the quiet side of the oasis where the palms thin out and the desert begins. An infinity pool that pours into the sand sea.",
    description: "Rooms are generous, calm, and thoughtfully designed.",
    pricePerNight: "€130 / night",
    imageUrl: "/attached_assets/talist-siwa_pooljpg.jpg",
    amenities: ["Infinity pool", "Desert panorama", "Spacious rooms", "Restaurant on site"],
    eco: false,
    luxury: false,
    isActive: true,
  },
  {
    slug: "siwa-shali-resort",
    name: "Siwa Shali Resort",
    destination: "siwa",
    category: "Resort",
    blurb:
      "A palm-shaded resort set between the old city walls and the date orchards, with a pool and gardens that feel genuinely lush.",
    description: "Best choice for families or those who want reliable amenities alongside the oasis experience.",
    pricePerNight: "€110 / night",
    imageUrl: "/attached_assets/siwa-shali-resort-.jpg",
    amenities: ["Swimming pool", "Palm gardens", "Old city location", "Family friendly"],
    eco: false,
    luxury: false,
    isActive: true,
  },
  {
    slug: "azad-siwa-hotel",
    name: "Azad Siwa Hotel",
    destination: "siwa",
    category: "Boutique Hotel",
    blurb:
      "A quietly considered boutique hotel in the centre of Siwa town. Rooftop views across the oasis, locally sourced meals.",
    description: "The most central option — useful if you plan to spend time in the medina on foot.",
    pricePerNight: "€95 / night",
    imageUrl: "/attached_assets/azad-siwa-hotel_1751832908544.jpg",
    amenities: ["Rooftop restaurant", "Central location", "Local cuisine", "Walking access"],
    eco: false,
    luxury: false,
    isActive: true,
  },
  {
    slug: "solei-old-town",
    name: "Soléi Old Town",
    destination: "siwa",
    category: "Heritage Stay",
    blurb:
      "Stone walls, cool interiors, a rooftop that overlooks the Shali fortress at dusk. A Soléi-owned property in the historic medina.",
    description: "Handcrafted clay rooms in the historic heart of Siwa.",
    pricePerNight: "€145 / night",
    imageUrl: "/attached_assets/solei-old-town-heritage.png",
    amenities: ["Rooftop terrace", "Shali views", "Heritage rooms", "Local breakfast"],
    eco: false,
    luxury: true,
    isActive: true,
  },
  {
    slug: "solei-royal",
    name: "Soléi Royal",
    destination: "siwa",
    category: "Premium Stay",
    blurb: "A premium Soléi-owned villa on the desert edge, with a private salt pool and walled garden.",
    description: "Full board available. Generous, calm, and entirely private.",
    pricePerNight: "€195 / night",
    imageUrl: "/attached_assets/soliel-royal_1751757316304.png",
    amenities: ["Private salt pool", "Walled garden", "Desert edge", "Full board option"],
    eco: false,
    luxury: true,
    isActive: true,
  },
  {
    slug: "solei-desert-retreat",
    name: "Soléi Desert Retreat",
    destination: "siwa",
    category: "Desert Lodge",
    blurb:
      "A small desert lodge on the salt flats — three rooms, fire-cooked meals, no light pollution. A complete remove.",
    description: "Soléi-owned. Full board because there is nowhere else to eat.",
    pricePerNight: "€240 / night · full board",
    imageUrl: "/attached_assets/Solei Desart Retret_1763854758404.png",
    amenities: ["3 rooms only", "Great Sand Sea", "No light pollution", "Fire-cooked meals", "Star-gazing deck"],
    eco: true,
    luxury: true,
    isActive: true,
  },
  {
    slug: "solei-salt-caves",
    name: "Soléi Salt Caves",
    destination: "siwa",
    category: "Wellness Retreat",
    blurb:
      "A retreat carved into Siwa's natural salt caves. Cave rooms, salt-air therapy, an ancient microclimate locals have used for centuries.",
    description: "Soléi-owned. Half board with a plant-forward menu and a daily salt-cave session.",
    pricePerNight: "€175 / night · half board",
    imageUrl: "/attached_assets/Solei Salt Caves_1763854758400.png",
    amenities: ["Cave rooms", "Salt air therapy", "Ancient microclimate", "Guided cave walks"],
    eco: true,
    luxury: true,
    isActive: true,
  },

  // ─── North Coast ─────────────────────────────────────────────
  {
    slug: "address-beach-resort-marassi",
    name: "Address Beach Resort Marassi",
    destination: "north-coast",
    category: "Luxury Resort",
    blurb:
      "Refined, unhurried, positioned directly on the water. The Marassi flagship — the coast at its most composed.",
    description: "Multiple pools, sea-facing rooms, fine dining, spa & wellness, kids club.",
    pricePerNight: "€290 / night",
    imageUrl: "/attached_assets/Address beach Resort _1758144493080.jpg",
    amenities: ["Private beach", "Multiple pools", "Sea-facing rooms", "Fine dining", "Spa & wellness", "Kids club"],
    eco: false,
    luxury: true,
    isActive: true,
  },
  {
    slug: "vida-marina-resort-marassi",
    name: "Vida Marina Resort Marassi",
    destination: "north-coast",
    category: "Luxury Resort",
    blurb:
      "Mediterranean-facing. Clean lines, open sea, and enough space to feel genuinely alone — by the marina.",
    description: "Marina views, beach access, rooftop pool, water sports.",
    pricePerNight: "€210 / night",
    imageUrl: "/attached_assets/Vida Marina Resort Marassi _1758142322079.jpg",
    amenities: ["Marina views", "Beach access", "Rooftop pool", "Water sports"],
    eco: false,
    luxury: true,
    isActive: true,
  },
  {
    slug: "address-marassi-golf-resort",
    name: "Address Marassi Golf Resort",
    destination: "north-coast",
    category: "Golf Resort",
    blurb: "An 18-hole championship course at Marassi with sea-view rooms and a clubhouse worth lingering at.",
    description: "Quieter than its sibling resorts. Suited to guests who play in the morning and rest properly in the afternoon.",
    pricePerNight: "€240 / night",
    imageUrl: "/attached_assets/Address Golf Resort_1758143858790.jpg",
    amenities: ["18-hole golf course", "Sea view rooms", "Clubhouse dining", "Spa access"],
    eco: false,
    luxury: true,
    isActive: true,
  },
  {
    slug: "casa-cook-north-coast",
    name: "Casa Cook North Coast",
    destination: "north-coast",
    category: "Boutique Resort",
    blurb:
      "Bohemian, warm, designed for people who travel slowly. Earthy tones, rattan, organic forms — every corner considered.",
    description: "Smaller, quieter, more considered. Adults-friendly.",
    pricePerNight: "€195 / night",
    imageUrl: "/attached_assets/Casa Cook North Coast _001_1758143858816.png",
    amenities: ["Design-led rooms", "Beach club", "Yoga & wellness", "Adults-friendly"],
    eco: false,
    luxury: true,
    isActive: true,
  },
  {
    slug: "jaz-almaza-beach-resort",
    name: "Jaz Almaza Beach Resort",
    destination: "north-coast",
    category: "Beach Resort",
    blurb: "Almaza Bay's clearest water. Family-friendly, all-inclusive available, never frenetic.",
    description: "Larger than Casa Cook but less frenetic than Marassi.",
    pricePerNight: "€175 / night",
    imageUrl: "/attached_assets/JAZ Almaza Beach-Resort_1758143858816.jpg",
    amenities: ["Private beach", "Crystal clear water", "Multiple restaurants", "Water sports centre"],
    eco: false,
    luxury: false,
    isActive: true,
  },
  {
    slug: "the-g-hotel-seashell",
    name: "The G Hotel Seashell",
    destination: "north-coast",
    category: "Boutique Hotel",
    blurb: "An intimate boutique resort at Almaza Bay with up to five-bedroom villas and direct white-sand beach access.",
    description: "Fewer rooms, more attention per guest, without the crowds of the larger resort complexes.",
    pricePerNight: "€185 / night",
    imageUrl: "/attached_assets/The G Hotel Seashell_1758142922930.png",
    amenities: ["5-bedroom villas", "Beach access", "Personalised service", "Quiet location"],
    eco: false,
    luxury: true,
    isActive: true,
  },
  {
    slug: "rixos-premium-alamein",
    name: "Rixos Premium Alamein",
    destination: "north-coast",
    category: "Premium Resort",
    blurb:
      "Premium all-inclusive done at its most comprehensive — private beach, restaurants, entertainment, and a genuinely expansive stretch of coast.",
    description: "Particularly suited to families or guests who want everything on site.",
    pricePerNight: "€260 / night",
    imageUrl: "/attached_assets/Rixos Premium Alamein_1758143858817.png",
    amenities: ["Ultra all-inclusive", "Private beach", "5 restaurants", "Premium spa", "Kids waterpark"],
    eco: false,
    luxury: true,
    isActive: true,
  },
  {
    slug: "al-alamein-hotel",
    name: "Al Alamein Hotel",
    destination: "north-coast",
    category: "Heritage Hotel",
    blurb:
      "A beachfront resort at historic Al Alamein with superior to family rooms, beach access, and proximity to the WWII Museum.",
    description: "Quieter, faded grandeur. Best for travellers who want to understand this part of Egypt more fully.",
    pricePerNight: "€175 / night",
    imageUrl: "/attached_assets/Al Alamein Hotel__1758143858816.png",
    amenities: ["Sea front position", "Heritage character", "Near WWII museum", "Quiet location"],
    eco: false,
    luxury: false,
    isActive: true,
  },
];

type SeedBlogPost = Omit<InsertBlogPost, "publishedAt"> & {
  publishedAt: Date;
};

export const seedBlogPosts: SeedBlogPost[] = [
  {
    slug: "why-siwa-oasis-should-be-your-next-escape",
    title: "Why Siwa Oasis Should Be Your Next Escape",
    excerpt:
      "Tucked away in Egypt's Western Desert, Siwa Oasis is a world apart — a place where ancient traditions, healing springs, and endless starlit skies create the ultimate digital detox.",
    content: [],
    category: "Siwa",
    coverImage: "/attached_assets/siwa-shali-resort-.jpg",
    author: "Soléi Editorial",
    publishedAt: new Date("2026-03-10"),
    readTime: 5,
    featured: true,
    tags: ["Siwa", "Desert", "Eco-Travel", "Wellness"],
    destination: "siwa",
    articleType: "guide",
    linkedExperience: null,
    isPublished: true,
  },
  {
    slug: "ultimate-guide-to-egypts-north-coast",
    title: "The Ultimate Guide to Egypt's North Coast",
    excerpt:
      "From the turquoise lagoons of Marassi to the historic shores of Al Alamein, Egypt's Mediterranean coastline is redefining luxury beach travel.",
    content: [],
    category: "North Coast",
    coverImage: "/attached_assets/Hotel-Beach.jpeg (1)_1751327157755.webp",
    author: "Soléi Editorial",
    publishedAt: new Date("2026-03-05"),
    readTime: 5,
    featured: true,
    tags: ["North Coast", "Beach", "Luxury", "Resorts"],
    destination: "north-coast",
    articleType: "guide",
    linkedExperience: null,
    isPublished: true,
  },
  {
    slug: "healing-waters-of-siwa-salt-lake-therapy",
    title: "The Healing Waters of Siwa: A Guide to Salt Lake Therapy",
    excerpt:
      "For centuries, Siwans have known what science is now confirming — the mineral-rich salt lakes of this remote oasis offer genuine therapeutic benefits for body and mind.",
    content: [],
    category: "Wellness",
    coverImage: "/attached_assets/salt-lake_1752975614632.jpg",
    author: "Soléi Editorial",
    publishedAt: new Date("2026-02-25"),
    readTime: 5,
    featured: false,
    tags: ["Wellness", "Salt Lakes", "Siwa", "Therapy"],
    destination: "siwa",
    articleType: "experience",
    linkedExperience: "salt-lake-float-therapy",
    isPublished: true,
  },
  {
    slug: "siwan-culture-traditions-you-should-know",
    title: "Siwan Culture: Traditions Every Visitor Should Know",
    excerpt:
      "Siwa's Amazigh community has preserved a distinct culture for millennia — from their own language to unique customs around hospitality, dress, and celebration.",
    content: [],
    category: "Culture",
    coverImage: "/attached_assets/Siwa Oracle Temple_1751926882739.jpg",
    author: "Soléi Editorial",
    publishedAt: new Date("2026-02-15"),
    readTime: 6,
    featured: false,
    tags: ["Culture", "Siwa", "Amazigh", "Traditions"],
    destination: "siwa",
    articleType: "guide",
    linkedExperience: null,
    isPublished: true,
  },
  {
    slug: "packing-for-the-desert-what-to-bring-to-siwa",
    title: "Packing for the Desert: What to Bring to Siwa",
    excerpt:
      "Siwa's remote location and desert climate mean packing smart is essential. Here's our tried-and-tested list for a comfortable oasis stay.",
    content: [],
    category: "Travel Tips",
    coverImage: "/attached_assets/Great_Sand_Sea_Adventures_1764706599725.PNG",
    author: "Soléi Editorial",
    publishedAt: new Date("2026-02-08"),
    readTime: 5,
    featured: false,
    tags: ["Travel Tips", "Packing", "Siwa", "Desert"],
    destination: "siwa",
    articleType: "guide",
    linkedExperience: null,
    isPublished: true,
  },
  {
    slug: "stargazing-in-siwa-guide-to-desert-night-sky",
    title: "Stargazing in Siwa: A Guide to the Desert Night Sky",
    excerpt:
      "With virtually zero light pollution, Siwa offers some of the darkest skies in North Africa. Here's how to make the most of a night under the stars.",
    content: [],
    category: "Siwa",
    coverImage: "/attached_assets/stargazing_1752963245806.jpg",
    author: "Soléi Editorial",
    publishedAt: new Date("2026-01-28"),
    readTime: 5,
    featured: false,
    tags: ["Stargazing", "Siwa", "Desert", "Astronomy"],
    destination: "siwa",
    articleType: "experience",
    linkedExperience: "desert-stargazing-experience",
    isPublished: true,
  },
];

type SeedExperience = Omit<InsertExperience, "pricePerPerson"> & {
  pricePerPerson: string;
};

/**
 * The 13 curated bundled tours that ship on the public site
 * (7 Siwa + 6 North Coast). Identified by slug + destination so
 * the admin can split them and the public pages can resolve them.
 */
export const seedExperiences: SeedExperience[] = [
  // ─── Siwa ────────────────────────────────────────────────
  {
    title: "Salt & Spring Escape",
    slug: "salt-and-spring-escape",
    destination: "siwa",
    category: "Water · Wellness",
    pricePerPerson: "60",
    duration: "Half day · 2–3 hours",
    maxGuests: 8,
    minAge: 6,
    difficulty: "Easy",
    summary: "A simple ritual of floating and renewal — salt, water, and stillness.",
    description:
      "The hyper-saline lakes hold you weightless at the sky's reflection, and Cleopatra's spring closes the loop with cool, clear water carved into the rock.",
    imageUrl: "/attached_assets/floating-in-spring_1753576589836.jpeg",
    mediaType: "image",
    eco: false,
    luxury: false,
    wellness: true,
    isActive: true,
  },
  {
    title: "Desert Sunset Experience",
    slug: "desert-sunset-experience",
    destination: "siwa",
    category: "Desert",
    pricePerPerson: "80",
    duration: "Sunset · 3–4 hours",
    maxGuests: 8,
    minAge: 8,
    difficulty: "Easy",
    summary: "A journey into the desert at golden hour — movement, silence, and sunset over endless dunes.",
    description:
      "A 4×4 across the Great Sand Sea, sandboarding down the largest dune, and tea at the highest point as the light gives out.",
    imageUrl: "/attached_assets/sand-boarding_1753576015281.png",
    mediaType: "image",
    eco: false,
    luxury: false,
    wellness: false,
    isActive: true,
  },
  {
    title: "Desert Night Experience",
    slug: "desert-night-experience",
    destination: "siwa",
    category: "Desert · Overnight",
    pricePerPerson: "150",
    duration: "Sunset → Morning",
    maxGuests: 8,
    minAge: 8,
    difficulty: "Easy",
    summary: "From sunset into the night — a complete desert experience ending under the stars.",
    description:
      "Safari, fire-cooked dinner in the open, a guide who reads the sky out loud, and a bed beneath a ceiling of stars.",
    imageUrl: "/attached_assets/sleeping-under-stars.jpg",
    mediaType: "image",
    eco: false,
    luxury: true,
    wellness: false,
    isActive: true,
  },
  {
    title: "Siwa Essential Experience",
    slug: "siwa-essential-experience",
    destination: "siwa",
    category: "Heritage · Water · Desert",
    pricePerPerson: "220",
    duration: "Full day",
    maxGuests: 8,
    minAge: 8,
    difficulty: "Easy",
    summary: "A full day designed to capture the essence of Siwa — water, desert, and silence.",
    description:
      "A heritage walk through Shali at the right hour, the salt and spring ritual at midday, then the dunes for an afternoon that ends in tea at the top of the world.",
    imageUrl: "/attached_assets/hero-image_1753576015270.png",
    mediaType: "image",
    eco: false,
    luxury: false,
    wellness: false,
    isActive: true,
  },
  {
    title: "Soléi Signature Siwa Journey",
    slug: "solei-signature-siwa-journey",
    destination: "siwa",
    category: "Premium · Private",
    pricePerPerson: "250",
    duration: "Full day → Night",
    maxGuests: 6,
    minAge: 8,
    difficulty: "Easy",
    summary: "The complete Siwa experience — from history to desert, from water to night.",
    description:
      "Heritage in the morning, salt and spring at midday, the sand sea by afternoon, dinner under the stars, and the option to wake up out there.",
    imageUrl: "/attached_assets/stargazing_1752963245806.jpg",
    mediaType: "image",
    eco: false,
    luxury: true,
    wellness: true,
    isActive: true,
  },
  {
    title: "Wellness & Sand Ritual",
    slug: "wellness-and-sand-ritual",
    destination: "siwa",
    category: "Wellness",
    pricePerPerson: "70",
    duration: "Half day · 2–3 hours",
    maxGuests: 6,
    minAge: 16,
    difficulty: "Easy",
    summary: "A traditional Siwan healing experience combined with moments of rest and calm.",
    description:
      "Buried in warm sand at the right hour by a local healer, then tea, shade, and the option to extend into a private massage.",
    imageUrl: "/attached_assets/Traditional Sand Bath Healing_1764121689995.JPG",
    mediaType: "image",
    eco: false,
    luxury: false,
    wellness: true,
    isActive: true,
  },
  {
    title: "Desert Stargazing",
    slug: "desert-stargazing",
    destination: "siwa",
    category: "Desert · Night",
    pricePerPerson: "55",
    duration: "Night · 3 hours",
    maxGuests: 8,
    minAge: 8,
    difficulty: "Easy",
    summary: "No light pollution. No noise. Just you, the sand, and the clearest sky you have ever seen.",
    description:
      "A guide who knows the constellations and the myths behind them, a blanket, and two hours that reframe the scale of everything.",
    imageUrl: "/attached_assets/stargazing_1752963245806.jpg",
    mediaType: "image",
    eco: false,
    luxury: false,
    wellness: false,
    isActive: true,
  },

  // ─── North Coast ─────────────────────────────────────────
  {
    title: "Private Yacht Sunset Ritual",
    slug: "private-yacht-sunset-ritual",
    destination: "north-coast",
    category: "Water · Private",
    pricePerPerson: "120",
    duration: "Sunset · 3 hours",
    maxGuests: 6,
    minAge: 6,
    difficulty: "Easy",
    summary: "An intimate escape into the Mediterranean at golden hour.",
    description:
      "The sea slows down, the light softens, and everything feels effortless — a private vessel, the coast in the distance, and a few hours where the day finally breathes out.",
    imageUrl: "/attached_assets/Pristine Beaches_1764585387661.jpg",
    mediaType: "image",
    eco: false,
    luxury: true,
    wellness: false,
    isActive: true,
  },
  {
    title: "Beach Club Experience",
    slug: "beach-club-experience",
    destination: "north-coast",
    category: "Leisure",
    pricePerPerson: "75",
    duration: "Day · Flexible",
    maxGuests: 8,
    minAge: 6,
    difficulty: "Easy",
    summary: "A seamless day at one of the North Coast's most refined beach clubs.",
    description:
      "Reserved seating, considered service, and the kind of slow afternoon that defines a coastal day done well.",
    imageUrl: "/attached_assets/water sports_1758262774773.jpg",
    mediaType: "image",
    eco: false,
    luxury: true,
    wellness: false,
    isActive: true,
  },
  {
    title: "Marassi Water World Experience",
    slug: "marassi-water-world-experience",
    destination: "north-coast",
    category: "Active · Leisure",
    pricePerPerson: "90",
    duration: "Full day",
    maxGuests: 12,
    minAge: 4,
    difficulty: "Easy",
    summary: "A vibrant day of energy and movement — slides, pools, and open-air moments.",
    description:
      "Full-day access to Marassi Water World, slides, pools & lazy river, poolside lounging areas, food & beverage available.",
    imageUrl: "/attached_assets/Water Sports_1764585780831.jpg",
    mediaType: "image",
    eco: false,
    luxury: false,
    wellness: false,
    isActive: true,
  },
  {
    title: "Signature Dinner Experience",
    slug: "signature-dinner-experience",
    destination: "north-coast",
    category: "Dining · Private",
    pricePerPerson: "140",
    duration: "Evening · 3 hours",
    maxGuests: 8,
    minAge: 6,
    difficulty: "Easy",
    summary: "An intimate dining moment by the sea — curated in location, mood, and detail.",
    description:
      "Whether it is a quiet table for two on the sand or a full private setup beneath the stars, the evening is shaped around how you want it to feel.",
    imageUrl: "/attached_assets/candlelit-dinner-outdoor_1752959631145.jpg",
    mediaType: "image",
    eco: false,
    luxury: true,
    wellness: false,
    isActive: true,
  },
  {
    title: "Nightlife Experience",
    slug: "nightlife-experience",
    destination: "north-coast",
    category: "Nightlife · Private",
    pricePerPerson: "110",
    duration: "Night · Flexible",
    maxGuests: 8,
    minAge: 18,
    difficulty: "Easy",
    summary: "Curated evenings across the North Coast's most refined venues.",
    description:
      "We handle the table, the access, and the route between, so the night feels handled before it begins.",
    imageUrl: "/attached_assets/candlelit-dinner-indoor_1752959631119.jpg",
    mediaType: "image",
    eco: false,
    luxury: true,
    wellness: false,
    isActive: true,
  },
  {
    title: "Coastal Wellness Ritual",
    slug: "coastal-wellness-ritual",
    destination: "north-coast",
    category: "Wellness",
    pricePerPerson: "130",
    duration: "Morning · Half day",
    maxGuests: 6,
    minAge: 14,
    difficulty: "Easy",
    summary: "A slow morning by the sea — designed to relax the body and clear the mind.",
    description:
      "Breathwork into movement into massage, with refreshments and time to do nothing afterwards.",
    imageUrl: "/attached_assets/morning-arond-the-pool_1752958525770.jpg",
    mediaType: "image",
    eco: false,
    luxury: true,
    wellness: true,
    isActive: true,
  },
];
